config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#home'
  get 'pages/about', to: 'pages#about'
  
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create' # for undefined method users_path
  resources :users, except: [:new] # other solution for error
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 
  resources :articles
  resources :categories, except: [:destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 3, maximum: 55500 }
  validates :user_id, presence: true
  
  
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category # belongs_to should be singular

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 4, maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  # methods in this controller are available to controllers but not views by default
  
  helper_method :current_user, :logged_in? # this makes available to views
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # return user if session user_id is in DB
    # return @current_user if already set, if not find the user and set current_user
  end
  
  def logged_in?
    !!current_user
    # returns true or false. Bang bang (!!)
    # true or false is the current_user logged in
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  # calling find params method for edit, update, show, destroy
  before_action :require_user, except: [:index, :show]
  # You need this so they have to be logged on to create a user
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def new
    @article = Article.new
  end
  
  def create
   # render plain: params[:article].inspect #show what was just created
    @article = Article.new(article_params) #white list values, create method #article_params
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
      if @article.update(article_params)
        flash[:success] = "Article was successfully updated"
        redirect_to article_path(@article)
      else
        render :edit
      end
  end
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 8)
  end
  
  def destroy # action
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :description, category_ids: []) # bracket because array form
      #top level key is article   
    end
  
    def set_article
      @article = Article.find(params[:id])
    end
  
  def require_same_user
    if current_user != @article.user and !current_user.admin?
      # current_user is declared in application_controller
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :find_category, only: [:show, :edit, :update]
  
  def index
   @categories = Category.paginate(page: params[:page], per_page: 8)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path      
    else
      render 'new'
    end    
  end
  
  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 8)
  end
  
  def edit
  
  end
  
  def update
    oldName = @category.name
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated from #{oldName} to #{@category.name}"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
    
  private 
  
  def category_params
    params.require(:category).permit(:name)
  end
    
  def find_category
    @category = Category.find(params[:id])
  end
  
  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was an issue with your login information"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]
  # You don't need require_user here because they 
  # can create without being logged in
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)  
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "User Account successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end    
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5) #instance variable
  end
  
  def destroy
    @user.destroy
    flash[:danger] = "User and all articles have been deleted"
    redirect_to users_path
  end
  
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user 
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end
  
  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end
end

app/views/articles/_articles.html.erb
<% obj.order('"IsCompleted" ASC').each do |article| %>  
<% if logged_in? && (current_user == article.user || current_user.admin?) %>

  <div class = 'col-xs-4'>
    <% if article.IsCompleted? %>
      <div class = 'well well-lg completed-feature'>
    <% else %>
    <div class = 'well well-lg'>
    <% end %>
      <div class = 'article-title'>
        <%= link_to article.title, article_path(article) %>
      </div>

        <div class = 'article-body'>  
       
        <%= truncate(article.description, length: 80) %>
          <div class = 'article-meta-details'>
          <small>
            Created by: <%= article.user.username if article.user %>
            <%= time_ago_in_words(article.created_at) %> ago,
            lasted updated: <%= time_ago_in_words(article.updated_at) %> ago
          </small>
          </div>
        </div>
      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>
      
        <div class = 'article-actions'>
          <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-xs btn-primary' %>
          <%= link_to 'Delete', article_path(article), method: :delete, 
              data: {confirm: "Are you sure you want to delete this article?"}, 
              class: 'btn btn-xs btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>

<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', errMessage: @article %>

<div class = 'row'>
  <div class = 'col-xs-12'>
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class = 'form-group'>
      <div class = 'control-label col-sm-2'>
          <%= f.label :title %>
      </div>
      <div class = 'col-sm-8'>
          <%= f.text_field :title, class: 'form-control', placeholder: "Feature", autofocus: true %>
      </div>
    </div>
        <div class = 'form-group'>
          <div class = 'control-label col-sm-2'>
          <%= f.label :description %>
          </div>
          <div class = 'col-sm-8'>
          <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: "Feature content" %>
          </div>
    </div>
    <div class = 'form-group'>
      <div class = 'row'>
         <div class = 'col-sm-offset-2 col-sm-10'>
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: 'checkbox-inline input_checkbox') {cb.check_box(class: 'checkbox') + cb.text} %>
           <% end %>
         </div>
      </div>
    </div>
       <div class = 'form-group'>
         <div class = 'col-sm-offset-2 col-sm-10'>
          <%= f.submit class: 'btn btn-primary btn-lg' %>
         </div>
    </div>
        <% end %>   
    <div class = 'col-xs-4 col-xs-offset-5'>
       [ <%= link_to 'Go Back', articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align = 'center'>
  Edit existing feature
</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align = 'center'>
  Listing All Features
</h1>
<div align = 'center'>
  <%= will_paginate %>
</div>
<%= render 'articles', obj: @articles %>
</div>

app/views/articles/new.html.erb
<h1 align = 'center'>
  Create a Feature
</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align = 'center'>
  Feature: <%= @article.title %>
</h2>
<div class = 'well col-xs-8 col-xs-offset-2'>
  <% if @article.user %>
   <ul class = 'listing'>
        <div class = 'row center'>
          <div class = 'col-md-4 col-md-offset-4'>
            <li>Created by:</li>
            <li>
              <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            </li>
            <li class = 'article-title'>
              <%= link_to @article.user.username, user_path(@article.user) %>
            </li>
            <li>
              <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
            </li>
          </div>
        </div>
    </ul>
  <% end %>
  <h4 class = 'center description'><strong>Description:</strong></h4>
  <hr>
    <%= simple_format(@article.description) %>
    <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
    <% end %>
  <div class = 'article-actions'>
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-xs btn-primary' %>
      <%= link_to ' Delete', article_path(@article), method: :delete, 
          data: {confirm: "Are you sure you want to delete this article?"}, 
          class: 'btn btn-xs btn-danger' %>
    <% end %>
    <%= link_to 'View all features', articles_path, class: 'btn btn-xs btn-success' %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class = 'badge'><%= link_to category.name, category_path(category) %> &nbsp;</span> 

app/views/categories/_form.html.erb
<%= render 'shared/errors', errMessage: @category %>

    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class = 'form-group'>
  <div class = 'control-label col-sm-2'>
      <%= f.label :name %>
  </div>
  <div class = 'col-sm-8'>
      <%= f.text_field :name, class: 'form-control', placeholder: "Project", autofocus: true %>
  </div>
</div>

   <div class = 'form-group'>
     <div class = 'col-sm-offset-2 col-sm-10'>
      <%= f.submit class: 'btn btn-primary btn-lg' %>
     </div>
</div>
    <% end %>
<div class = 'col-xs-4 col-xs-offset-5'>
   [ <%= link_to 'Go Back', articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align = 'center'>
  Edit Project [<%= @category.name %>]
</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align = 'center'>
  Listing All Projects
</h1>
 
<div align = 'center'>
<%= will_paginate %>
<% @categories.each do |category| %>
    <ul class = 'listing'>
      <div class = 'row'>
        <div class = 'well col-md-4 col-md-offset-4'>
          <li class = 'article-title'>
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li><small><%= pluralize(category.articles.count, "article") %></small></li>
          <% if logged_in? and current_user.admin? %>
          <li><small><%= link_to 'Edit', edit_category_path(category) %> </small></li>
          <% end %>
        </div>
      </div>
    </ul>
<% end %>
</div>
  

app/views/categories/new.html.erb
<h1 align = 'center'>
  Create New Project
</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align = 'center'>
  <%= "Project: " + @category.name %>
</h1>
<div align = 'center'>
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/articles', obj: @category_articles %>
<div align = 'center'>
</div>

app/views/layouts/_adminalert.html.erb
<% if logged_in? && current_user.admin? %>
<div class = 'row'>
  <div class = 'col-xs-10 col-xs-offset-1'>
    <div class = 'alert alert-warning'>
      <div class = 'adminalert'>
        <small>
          Admin Account
        </small>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class ="container">
  <footer class ="footer">
  <small>Copyright &copy; Alpha Blog 2018 by Austin</small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", pages_about_path %></li>
    </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class = 'row'>
  <div class = 'col-xs-10 col-xs-offset-1'>
<% flash.each do |name, msg| %>
    <div class = 'alert alert-<%= "#{name}" %>'>
      <a href = '#' class = 'close' data-dismiss = 'alert'>
        &#215;
      </a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
<% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- This is what it was previously <a class="navbar-brand" id ="logo" href="#">Alpha</a> -->
      <%= link_to "Alpha", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Features", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create Feature", new_article_path %> </li>
             
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Projects", categories_path %> </li>
              <li role="separator" class="divider"></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name} (#{category.articles.count})", category_path(category)%></li> 
              <% end %>
               <% if logged_in? and current_user.admin? %>
               <li role="separator" class="divider"></li>
              <li><%= link_to "Create Project", new_category_path %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Settings <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
            <li><%= link_to 'View Profile', user_path(current_user) %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
          <li><%= link_to 'Profile', user_path(current_user) %></li>
          <li><%= link_to 'Log Out', logout_path, method: :delete  %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewAlpha</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/adminalert' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>
  About Blog
</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in commodo velit, at sodales lorem. Mauris ullamcorper orci vitae consectetur mollis. Donec eleifend ipsum ut nulla suscipit, at tempor ipsum interdum. Vestibulum condimentum placerat risus, eget posuere nulla tempor sodales. Donec viverra consectetur erat. Donec interdum aliquam nulla nec laoreet. Vestibulum nec lorem lacinia libero porttitor molestie. Suspendisse potenti. Aenean id tincidunt mi, vel aliquam nisl. Vivamus eu risus in mauris feugiat elementum.
<br><br>
Aenean neque quam, egestas in feugiat quis, suscipit ac nisl. Integer feugiat elementum erat, nec egestas quam ultricies eu. Pellentesque enim nunc, aliquam non imperdiet quis, molestie in nulla. Donec vitae purus dictum, euismod mi eget, varius turpis. Nam lorem erat, dictum sed ligula nec, dignissim pulvinar ex. Maecenas dictum sit amet tellus non maximus. Curabitur aliquet ac metus quis consectetur. Nunc fringilla euismod tincidunt. Proin eget dignissim odio, quis placerat neque.
<br><br>
Vivamus efficitur ante in convallis pulvinar. Cras nibh tellus, pretium id sapien et, ornare feugiat metus. Pellentesque ultricies erat id nulla tempus luctus. Curabitur placerat neque et urna pellentesque semper. Pellentesque dapibus, nunc vel posuere fringilla, orci purus viverra lectus, sed pretium leo felis quis turpis. Praesent vitae ipsum ornare nunc tincidunt varius. Nullam quis dolor ac purus lobortis rhoncus ac ac diam. Vivamus volutpat porttitor nulla, vel blandit eros suscipit et. Nullam tincidunt, nulla sit amet rhoncus tincidunt, libero diam iaculis diam, at hendrerit purus est ac erat. Mauris ullamcorper, turpis in sagittis lobortis, neque odio interdum orci, condimentum scelerisque dolor felis et orci. Proin at pulvinar ipsum, non ornare mauris. Aenean posuere nisi justo, quis faucibus purus commodo quis. Morbi eget nisl tempor, semper massa ac, accumsan elit. Fusce at magna viverra, gravida justo ac, dapibus orci. Curabitur ut accumsan elit. Fusce gravida quis lectus vel rhoncus.
<br><br>
Praesent interdum dictum elit ut sollicitudin. Maecenas ullamcorper ac justo nec aliquet. Aliquam erat volutpat. Nulla maximus vulputate diam, non dignissim metus volutpat non. Fusce tristique cursus est at aliquet. Sed sed odio commodo, molestie velit sed, pulvinar mauris. Maecenas velit ligula, aliquet a pellentesque id, dapibus sed enim. Aenean nibh ante, laoreet eu lectus sed, auctor iaculis augue. Curabitur ut diam est. Etiam dolor justo, aliquam et metus venenatis, lobortis mollis magna. Sed suscipit aliquet tellus eu lacinia. Praesent blandit commodo enim, sit amet gravida elit hendrerit nec. Pellentesque nec sem justo. Nullam eu scelerisque diam, ut pellentesque nunc.
<br><br>
Suspendisse congue mi dui, vitae mollis sem eleifend quis. Praesent tellus turpis, sollicitudin vitae hendrerit eget, pellentesque eget odio. Phasellus lacinia nulla a odio feugiat luctus. Vestibulum ut luctus turpis. Cras vehicula pulvinar dolor, vel condimentum leo porta id. In vel risus nec turpis feugiat lacinia. Etiam lacinia, dolor euismod tristique ultricies, ante mi placerat massa, a fringilla urna tortor nec erat. Vivamus imperdiet sem luctus ex feugiat, at ornare eros mattis. Integer a arcu nunc.
</p>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Alpha Blog</h1>
  <%= link_to "Sign up now", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

<h1>
  Welcome
</h1>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis ex a massa aliquet posuere sit amet blandit tellus. Vestibulum sed velit ac enim ultrices semper. Praesent volutpat venenatis tellus, malesuada rhoncus nunc pulvinar eu. Vivamus et facilisis ipsum. In molestie erat orci. Fusce blandit sem vitae urna imperdiet vehicula. Morbi lobortis purus volutpat leo fermentum, sed dictum libero bibendum.
</p>
<p>
Cras in blandit libero, non convallis nibh. Vestibulum commodo eget neque vel feugiat. Mauris at augue nec nibh tempor ultrices. Nam tristique, turpis ut facilisis malesuada, enim purus vestibulum leo, condimentum rhoncus eros turpis sit amet purus. Curabitur mattis ligula cursus tortor tristique laoreet. Morbi justo nunc, efficitur sit amet porttitor in, elementum a lectus. Etiam mollis nisi sed libero pulvinar, sed molestie ipsum accumsan. Donec at semper ante. Phasellus sit amet arcu aliquet dui varius malesuada in in diam. Sed vehicula quis urna sed elementum. Nulla dictum massa sed augue lacinia, quis condimentum neque fermentum. Nullam mollis mattis velit, ut tristique mi. Nullam sodales in purus faucibus luctus. Nullam erat leo, efficitur non gravida eu, condimentum ut ligula.
</p>

app/views/shared/_errors.html.erb
<% if errMessage.errors.any? %>
  <div class = 'row'>
    <div clas = 'col-xs-8 col-xs-offset-2'>
      <div class = 'panel panel-danger'>
        <div class = 'panel-heading'>
          <h2 class = 'panel-title'>
            <%= pluralize(errMessage.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <div class = 'panel-body'>
            <ul>
              <% errMessage.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
          </div>
      </div>
    </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', errMessage: @user %>

<div class = 'row'>
  <div class = 'col-xs-12'>
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class = 'form-group'>
      <div class = 'control-label col-sm-2'>
          <%= f.label :username %>
      </div>
      <div class = 'col-sm-8'>
          <%= f.text_field :username, class: 'form-control', placeholder: "Enter username", autofocus: true %>
      </div>
    </div>
        <div class = 'form-group'>
          <div class = 'control-label col-sm-2'>
          <%= f.label :email %>
          </div>
          <div class = 'col-sm-8'>
          <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
          </div>  
        </div>
            <div class = 'form-group'>
          <div class = 'control-label col-sm-2'>
          <%= f.label :password %>
          </div>
          <div class = 'col-sm-8'>
          <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
          </div>  
        </div>
       <div class = 'form-group'>
         <div class = 'col-sm-offset-2 col-sm-10'>
          <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: 'btn btn-primary btn-lg') %>
         </div>
    </div>
        <% end %>
    <div class = 'col-xs-4 col-xs-offset-5'>
       [ <%= link_to 'Go Back', articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align = 'center'>
  Edit Your Account
</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1 align='center'>
   Sign Up for alpha blog
</h1>

<%= render 'form' %>